# site
title: Louie
theme: louie

baseurl: /amzoyang.github.io
url: amzoyang.github.io
favicon: "/assets/sample/ico.png"
g_analytics: UA-12345678-1

# bio
header: Hi, I'm Amber Yang.
desc: >
  I'm a Computer Science and Physics student at Stanford. I spent a quarter abroad this year studying Philosophy at Oxford.

  At Stanford, I'm doing computational neutrino research under Hirohisa Tanaka at the Stanford Linear Accelerator Center, lead the talk series #nofilter, and ama VP at BASES (entrepreneurship club).

  In addition to school, I started SeerTracking, a space tech company that created a machine learning software to help satellite and space launch companies predict collisions with space debris. 

 <br> I've also dabbled a bit in VC and am a partner at Dorm Room Fund.

 <br> Currently Reading: On Earth We're Briefly Gorgeous by Ocean Vuong

# posts
date_format: "%Y"
post_title: Story
post_date: Year
post_cat: Genre

# post detail
prev-next: true

# build settings
markdown: kramdown
# theme: louie
exclude:
  - Gemfile
  - Gemfile.lock
