# site
title: Amber Yang
theme: louie

baseurl: ""
url: amzoyang.github.io
favicon: "/assets/sample/ico.png"
g_analytics: UA-12345678-1

# bio
header: Hi, I'm Amber Yang.
desc: >
  The majority of my time is spent thinking about creating a sustainable space environment for satellites as the founder at <mark>Seer Tracking</mark>, which led me to be named <mark>Forbes 30 Under 30</mark>.<br><br> I'm a Computer Science and Physics student at <mark>Stanford</mark> and spent a quarter abroad studying Philosophy at Oxford. I've also dabbled a bit in VC and am a partner at <mark>Dorm Room Fund</mark>.<br><br> I'm always open to chatting about space, philosophy, politics, and literature. The best way to reach me is at amber.yang@seertracking.com
  <br><br> Currently Reading: How Democracies Die

# posts
date_format: "%Y"
post_title: Blog
post_date: Date
post_cat: Type

# post detail
prev-next: true

# build settings
markdown: kramdown
# theme: louie
exclude:
  - Gemfile
  - Gemfile.lock
